### ISSUE TITLE
I accidentally click the back button when I want to close a device detail view

### ISSUE THREAD

**Issue by haptipedia-community** [haptipedia/haptipedia#15]
I have repeatedly clicked my browser's back button when I wanted to close a device detail view.  This is irritating because it takes me away from the Haptipedia device browser.  To me, the visual clues are not clear that the device details are a modal window (pop-up) in front of the device gallery.  

I also had problems when I clicked a different device in the device details window, and it took me to that device.  I expected that clicking back would take me to the device I was looking at before, but it doesn't!  Instead it takes me away from Haptipedia, which makes me sad.

**Comment by michael-oppermann** [comment]
The browser navigation (e.g., back button) is now compatible with Haptipedia's single-page design. If you open a new device from a detail page you can use the back button to go to the previous one.

In the future we will work on the visual clues to make it more clear that devices are displayed in a modal window.
