### ISSUE TITLE
Bug with Bookmarking Devices

### ISSUE THREAD

**Issue by haptipedia-community** [haptipedia/haptipedia#40]
Device: Stanford2DOF2017b (Haplink)
--

If I bookmark a device on its device page with the "Add to Bookmarks" button, it turns into "Remove from Bookmarks", but then if I return to the device gallery, then click on the device from the device gallery again to view its device page, the button should be "Remove from Bookmarks" because the device has already been added but its still "Add to Bookmarks".

**Comment by michael-oppermann** [comment]
Seems like this problem occurred in Safari. It works now.
